controllers:
    resource: ../src/Controller/
    type: attribute

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

    # app_cgv:
    # path: /cgv
    # controller: Symfony\Bundle\FrameworkerBundle\Controller\TemplateController
    # defaults:
      # template: 'statique/cgv.html.twig'
